package api

import (
	"fmt"
	"os"
	"strings"

	"github.com/os-baka/backend/internal/model"
)

const dnsmasqHostsDir = "/etc/dnsmasq.d"
const dnsmasqMainConfig = "/etc/dnsmasq.d/00-main.conf"
const dnsmasqHostsConfig = "/etc/dnsmasq.d/01-hosts.conf"

// GenerateDnsmasqConfig generates the complete dnsmasq configuration
func GenerateDnsmasqConfig() error {
	// Generate main config
	if err := generateMainConfig(); err != nil {
		fmt.Printf("Warning: Could not generate main dnsmasq config: %v\n", err)
	}

	// Generate hosts config
	if err := generateHostsConfig(); err != nil {
		fmt.Printf("Warning: Could not generate hosts dnsmasq config: %v\n", err)
	}

	return nil
}

// generateMainConfig generates the main dnsmasq configuration from DB
func generateMainConfig() error {
	var config model.DHCPConfig
	result := getDB().Where("is_active = ?", true).First(&config)
	if result.Error != nil {
		// No active config, use defaults
		return nil
	}

	var content strings.Builder
	content.WriteString("# Auto-generated by OS-Baka\n")
	content.WriteString("# Do not edit manually - changes will be overwritten\n\n")

	// Force bind to all interfaces for host network usage in Docker
	// Since we are running with network_mode: host, we want to listen on all appropriate interfaces
	// or rely on dnsmasq's default behavior, but the user requested "bind 0.0.0.0".
	// Dnsmasq doesn't use 0.0.0.0 directly in config, but we can omit 'interface=' or use specific flags.
	// However, if we want to respect the user's "unconditional bind", we usually remove interface restrictions.

	// If the user selects an interface in UI, we might still want to prioritize it, OR
	// typically if running host mode container, we just bind wild.
	// The user asked "unconditional bind 0.0.0.0", which usually means:
	// except-interface=lo
	// bind-dynamic
	// OR just listing interfaces.

	// Let's implement what is requested: remove the specific interface binding restriction
	// and allow it to listen on the selected interface explicitly if provided, but also ensure it works across host.

	// Actually, the user says "I want to bind 0.0.0.0 ... so other machines can access".
	// This implies removing `bind-interfaces` which restricts it to only interfaces up at start,
	// and ensuring we don't limit to loopback.

	if config.Interface != "" {
		// If interface acts as a filter
		fmt.Fprintf(&content, "interface=%s\n", config.Interface)
	}
	// content.WriteString("bind-interfaces\n\n") -- Removing this as it's too restrictive for some docker setups

	// DHCP Range
	fmt.Fprintf(&content, "dhcp-range=%s,%s,%s,%s\n",
		config.RangeStart, config.RangeEnd, config.SubnetMask, config.LeaseTime)

	// Gateway
	if config.Gateway != "" {
		fmt.Fprintf(&content, "dhcp-option=option:router,%s\n", config.Gateway)
	}

	// DNS Server
	if config.DNSServer != "" {
		fmt.Fprintf(&content, "dhcp-option=option:dns-server,%s\n", config.DNSServer)
	}

	// Domain
	if config.Domain != "" {
		fmt.Fprintf(&content, "domain=%s\n", config.Domain)
	}

	content.WriteString("\n")

	// PXE Boot Configuration
	if config.EnablePXE {
		content.WriteString("# PXE Boot Configuration\n")
		content.WriteString("enable-tftp\n")
		content.WriteString("tftp-root=/tftpboot\n\n")

		// BIOS clients
		content.WriteString("# BIOS PXE Boot\n")
		content.WriteString("dhcp-match=set:bios,option:client-arch,0\n")
		bootFile := config.BootFile
		if bootFile == "" {
			bootFile = "undionly.kpxe"
		}
		if config.NextServer != "" {
			fmt.Fprintf(&content, "dhcp-boot=tag:bios,%s,,%s\n\n", bootFile, config.NextServer)
		} else {
			fmt.Fprintf(&content, "dhcp-boot=tag:bios,%s\n\n", bootFile)
		}

		// UEFI clients
		content.WriteString("# UEFI PXE Boot\n")
		content.WriteString("dhcp-match=set:efi64,option:client-arch,7\n")
		content.WriteString("dhcp-match=set:efi64,option:client-arch,9\n")
		content.WriteString("dhcp-boot=tag:efi64,ipxe.efi\n\n")

		// iPXE chainloading
		content.WriteString("# iPXE Chainloading\n")
		content.WriteString("dhcp-match=set:ipxe,175\n")

		// Determine server IP for HTTP boot
		// This should be the external IP address of the server running Nginx/Backend
		serverIP := config.BootServerIP
		if serverIP == "" {
			serverIP = config.NextServer
		}
		// Use static external IP from environment if available (robust Docker default)
		extIP := os.Getenv("EXTERNAL_IP")
		fmt.Printf("DEBUG: EXTERNAL_IP env var: '%s'\n", extIP)
		if serverIP == "" {
			serverIP = extIP
		}
		if serverIP == "" {
			serverIP = config.TFTPServer
		}
		if serverIP == "" {
			serverIP = config.Gateway
		}
		if serverIP == "" {
			// Absolute fallback
			serverIP = "192.168.10.1"
		}

		// Use port 80 (Nginx) which proxies to backend:8000
		// We point to a static init script which handles the variable expansion safely within iPXE
		fmt.Fprintf(&content, "dhcp-boot=tag:ipxe,http://%s/api/v1/pxe/init\n\n", serverIP)
	}

	content.WriteString("# Logging\n")
	content.WriteString("log-dhcp\n")

	// Write to file
	if err := os.WriteFile(dnsmasqMainConfig, []byte(content.String()), 0644); err != nil {
		return err
	}

	// Create reload trigger file
	if err := os.WriteFile(dnsmasqHostsDir+"/.reload", []byte("reload"), 0644); err != nil {
		fmt.Printf("Warning: Could not create reload trigger: %v\n", err)
	}

	return nil
}

// generateHostsConfig generates DHCP reservations from both nodes and explicit reservations
func generateHostsConfig() error {
	var content strings.Builder
	content.WriteString("# Auto-generated DHCP Host Reservations by OS-Baka\n")
	content.WriteString("# Do not edit manually - changes will be overwritten\n\n")

	// Get active DHCP reservations
	var reservations []model.DHCPReservation
	getDB().Where("is_active = ?", true).Find(&reservations)

	if len(reservations) > 0 {
		content.WriteString("# Explicit DHCP Reservations\n")
		for _, r := range reservations {
			if r.MACAddress != "" && r.IPAddress != "" {
				// Format: dhcp-host=<mac>,<ip>,<hostname>
				if r.Hostname != "" {
					fmt.Fprintf(&content, "dhcp-host=%s,%s,%s\n",
						r.MACAddress, r.IPAddress, r.Hostname)
				} else {
					fmt.Fprintf(&content, "dhcp-host=%s,%s\n",
						r.MACAddress, r.IPAddress)
				}
			}
		}
		content.WriteString("\n")
	}

	// Get nodes that don't have explicit reservations
	var nodes []model.Node
	getDB().Find(&nodes)

	// Create a map of existing reservations
	reservedMACs := make(map[string]bool)
	for _, r := range reservations {
		reservedMACs[strings.ToLower(r.MACAddress)] = true
	}

	// Add nodes that aren't already reserved
	nodeReservations := 0
	for _, node := range nodes {
		if node.MACAddress == "" || node.IPAddress == "" {
			continue
		}
		if reservedMACs[strings.ToLower(node.MACAddress)] {
			continue
		}

		if nodeReservations == 0 {
			content.WriteString("# Node-based Reservations\n")
		}

		if node.Hostname != "" {
			fmt.Fprintf(&content, "dhcp-host=%s,%s,%s\n",
				node.MACAddress, node.IPAddress, node.Hostname)
		} else {
			fmt.Fprintf(&content, "dhcp-host=%s,%s\n",
				node.MACAddress, node.IPAddress)
		}
		nodeReservations++
	}

	// Write to file
	if err := os.WriteFile(dnsmasqHostsConfig, []byte(content.String()), 0644); err != nil {
		return err
	}

	return nil
}

// UpdateDnsmasqForNode updates the dnsmasq config after a node is added/modified
func UpdateDnsmasqForNode(node *model.Node) error {
	return GenerateDnsmasqConfig()
}

// RemoveDnsmasqForNode updates the dnsmasq config after a node is deleted
func RemoveDnsmasqForNode(node *model.Node) error {
	return GenerateDnsmasqConfig()
}
