package api

import (
	"fmt"

	"github.com/os-baka/backend/internal/model"
)

// statusCallbackAttempts and statusCallbackSleep tune the retry loop the
// postinstall script uses to update node status to `active`. 5 * 10s
// gives the box ~50 seconds to recover from a transient network issue
// (slow DHCP, DNS resolver init, backend rolling restart) before giving
// up. Failure mode is recoverable — script keeps itself + unit on disk
// so systemd retries on next boot.
const (
	statusCallbackAttempts = 5
	statusCallbackSleepSec = 10
)

// buildPostinstallScript returns the bash script that systemd runs on
// first boot. The shape is:
//
//   1. Retry curl PUT /internal/nodes/:id/status (status=active) up to
//      statusCallbackAttempts times.
//   2. If the callback never succeeded: exit 0 WITHOUT cleanup so
//      systemd retries on the next boot. This is the F fix — previously
//      cleanup ran unconditionally, so a single failed callback (network
//      blip, backend restart) left the node stuck in `installing` until
//      the watcher timed it out into `error`.
//   3. On success: run hostnamectl, enable sshd, run SSH-root + TPM
//      blocks (each independently best-effort), then disable the unit
//      and remove the script + unit file so we don't run again.
//
// Args:
//   - backendURL: http://<EXTERNAL_IP>; the URL prefix the callback
//     hits. Embedded at preseed time, so a backend IP change after
//     install means the callback can never succeed — operator has to
//     manually clear `installing` or rebuild.
//   - sshRootLoginSetup / tpmSetup: pre-rendered shell blocks for the
//     two optional features. Empty strings if disabled.
func buildPostinstallScript(node *model.Node, backendURL, sshRootLoginSetup, tpmSetup string) string {
	return fmt.Sprintf(`#!/bin/bash
# Post-installation script for %s
# Generated by OS-Baka

set +e  # Don't exit on errors — we want fine-grained retry control

echo "OS-Baka: Running post-installation..."

# Step 1: report status=active to backend, with retries. This is the
# load-bearing step: failure here means the node never leaves the
# installing state. Other steps are best-effort and wont block
# cleanup if they fail.
STATUS_UPDATED=false
for attempt in $(seq 1 %d); do
    if curl -sfS -X PUT "%s/api/v1/internal/nodes/%d/status" \
         -H "Content-Type: application/json" \
         -d '{"status": "active"}'; then
        STATUS_UPDATED=true
        echo "OS-Baka: status callback succeeded on attempt $attempt"
        break
    fi
    echo "OS-Baka: status callback attempt $attempt failed; retrying in %ds"
    sleep %d
done

if [ "$STATUS_UPDATED" != "true" ]; then
    echo "OS-Baka: status callback failed after %d attempts" >&2
    echo "OS-Baka: keeping postinstall.sh + unit on disk; systemd will retry next boot" >&2
    exit 0
fi

# From here on: callback succeeded, do best-effort config + cleanup.

# Basic system configuration
hostnamectl set-hostname %s 2>/dev/null || echo "Warning: Failed to set hostname"

# Enable SSH (try both service names)
systemctl enable sshd 2>/dev/null || systemctl enable ssh 2>/dev/null || true
systemctl start sshd 2>/dev/null || systemctl start ssh 2>/dev/null || true
%s%s
# Remove this script and service after execution
rm -f /root/postinstall.sh
systemctl disable osbaka-postinstall.service 2>/dev/null || true
rm -f /etc/systemd/system/osbaka-postinstall.service

echo "OS-Baka: Post-installation complete!"
exit 0
`,
		node.Hostname,
		statusCallbackAttempts,
		backendURL, node.ID,
		statusCallbackSleepSec,
		statusCallbackSleepSec,
		statusCallbackAttempts,
		node.Hostname,
		sshRootLoginSetup, tpmSetup,
	)
}
