-- Baseline schema for OS-Baka.
--
-- Generated by capturing the exact DDL that GORM's AutoMigrate produced for
-- the model definitions at the time of the baseline freeze. Preserves the
-- GORM-mangled IPMI column names (ip_mi_address, ip_mi_username,
-- ip_m_ipassword, ip_mi_allow_untrusted) because that is what AutoMigrate
-- produced; migration 000003 renames them to the intended ipmi_* names and
-- the model now uses explicit gorm:"column:..." tags to keep them in sync.
--
-- New columns and indexes after this baseline live in subsequent numbered
-- migrations.

BEGIN;

-- ── users ──
CREATE TABLE users (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz,
    email text,
    username text,
    full_name text,
    password text,
    is_superuser boolean
);
CREATE INDEX idx_users_deleted_at ON users (deleted_at);
CREATE UNIQUE INDEX idx_user_email_active    ON users (email)    WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_user_username_active ON users (username) WHERE deleted_at IS NULL;

-- ── nodes ──
CREATE TABLE nodes (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz,
    hostname text,
    ip_address text,
    mac_address text,
    asset_tag text,
    status text,
    os_type text,
    os_version text,
    mirror_url text,
    timezone text,
    root_password text,
    ssh_enabled boolean,
    ssh_root_login boolean,
    encryption_enabled boolean,
    encryption_passphrase text,
    tpm_enabled boolean,
    usb_key_required boolean,
    pcr_binding text,
    -- GORM-mangled IPMI columns. Renamed by migration 000003.
    ip_mi_address text,
    ip_mi_username text,
    ip_m_ipassword text,
    ip_mi_allow_untrusted boolean,
    last_heartbeat timestamptz,
    cpu_usage numeric,
    memory_usage numeric,
    disk_usage numeric,
    uptime bigint,
    group_id bigint
);
CREATE INDEX idx_nodes_deleted_at ON nodes (deleted_at);
CREATE UNIQUE INDEX idx_node_mac_active ON nodes (mac_address) WHERE deleted_at IS NULL;

-- ── node_groups ──
CREATE TABLE node_groups (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    updated_at timestamptz,
    name text,
    description text,
    color text
);
CREATE UNIQUE INDEX idx_node_groups_name ON node_groups (name);

-- ── node_tags ──
CREATE TABLE node_tags (
    id bigserial PRIMARY KEY,
    node_id bigint,
    key text,
    value text
);
CREATE INDEX idx_node_tags_node_id ON node_tags (node_id);
CREATE INDEX idx_node_tags_key     ON node_tags (key);

-- ── dhcp_configs ──
CREATE TABLE dhcp_configs (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz,
    name text,
    interface text DEFAULT 'eth0',
    range_start text,
    range_end text,
    subnet_mask text DEFAULT '255.255.255.0',
    gateway text,
    dns_server text,
    lease_time text DEFAULT '12h',
    domain text DEFAULT 'os-baka.local',
    tftp_server text,
    boot_file text DEFAULT 'undionly.kpxe',
    next_server text,
    boot_server_ip text,
    mirror_url text,
    kernel_params text,
    is_active boolean DEFAULT false,
    enable_pxe boolean DEFAULT true
);
CREATE INDEX idx_dhcp_configs_deleted_at ON dhcp_configs (deleted_at);
CREATE UNIQUE INDEX idx_dhcp_configs_name ON dhcp_configs (name);

-- ── dhcp_reservations ──
CREATE TABLE dhcp_reservations (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz,
    mac_address text,
    ip_address text,
    hostname text,
    description text,
    is_active boolean DEFAULT true
);
CREATE INDEX idx_dhcp_reservations_deleted_at ON dhcp_reservations (deleted_at);
CREATE UNIQUE INDEX idx_dhcp_reservations_mac_address ON dhcp_reservations (mac_address);

-- ── boot_assets ──
CREATE TABLE boot_assets (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz,
    name text,
    file_name text,
    type text,
    size bigint,
    path text,
    check_sum text
);
CREATE INDEX idx_boot_assets_deleted_at ON boot_assets (deleted_at);

-- ── notifications ──
CREATE TABLE notifications (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz,
    title text,
    message text,
    type text,
    read boolean,
    user_id bigint
);
CREATE INDEX idx_notifications_deleted_at ON notifications (deleted_at);

-- ── audit_logs ──
CREATE TABLE audit_logs (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    action text,
    user_id bigint,
    username text,
    resource text,
    resource_id text,
    details text,
    ip_address text
);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);

-- ── api_keys ──
CREATE TABLE api_keys (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    updated_at timestamptz,
    name text,
    prefix text,
    key_hash text,
    role text,
    created_by bigint,
    last_used_at timestamptz,
    expires_at timestamptz,
    is_active boolean DEFAULT true
);
CREATE UNIQUE INDEX idx_api_keys_prefix ON api_keys (prefix);
CREATE INDEX idx_api_keys_key_hash ON api_keys (key_hash);

-- ── pxe_provisioning_tokens ──
CREATE TABLE pxe_provisioning_tokens (
    id bigserial PRIMARY KEY,
    created_at timestamptz,
    node_id bigint,
    token_hash text,
    client_ip text,
    expires_at timestamptz,
    consumed_at timestamptz
);
CREATE INDEX idx_pxe_provisioning_tokens_node_id ON pxe_provisioning_tokens (node_id);
CREATE INDEX idx_pxe_provisioning_tokens_expires_at ON pxe_provisioning_tokens (expires_at);
CREATE UNIQUE INDEX idx_pxe_provisioning_tokens_token_hash ON pxe_provisioning_tokens (token_hash);

COMMIT;
