name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build Backend
      working-directory: ./backend
      run: go build -v ./cmd/server

    - name: Build Backend Docker image
      run: docker build ./backend --file ./backend/Dockerfile --tag osbaka-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    - name: Build Frontend Docker image
      run: docker build ./frontend --file ./frontend/Dockerfile --tag osbaka-frontend:latest
